"""
Generate WALKTHROUGH.md and the walkthrough/ JSON artifacts from real output.

This is the Week 1 demo deliverable: "Walk through one sample document and show
exactly what the future Chunk objects must contain." Nothing in the generated
document is typed by hand, so it cannot describe an object the code does not
actually produce.

Usage:  python3 tools/build_walkthrough.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.ingest import chunks, extract, validate
from src.schema import ChunkerConfig, citation_targets

SAMPLE = ROOT / 'fixtures' / 'normal' / 'normal_nrc_reactor_concepts_ch01.pdf'
OUT = ROOT / 'walkthrough'


def j(obj, indent=2):
    return json.dumps(obj, indent=indent, ensure_ascii=False)


def main():
    OUT.mkdir(exist_ok=True)
    config = ChunkerConfig()

    result = validate(SAMPLE)
    doc_meta = result.document
    text, pages, handle = extract(SAMPLE)
    handle.close()
    cs = chunks(SAMPLE, config)

    spanning = [c for c in cs if c.spans_pages]
    first = cs[0]
    example = spanning[0] if spanning else cs[0]
    targets = citation_targets(example)

    # Artifacts a reviewer can open alongside the narrative.
    (OUT / 'validation_result.json').write_text(j(result.to_dict()) + '\n')
    (OUT / 'document.json').write_text(j(doc_meta) + '\n')
    (OUT / 'chunk_000.json').write_text(j(first.to_dict()) + '\n')
    (OUT / 'all_chunks.json').write_text(
        j({'document_id': doc_meta['document_id'],
           'chunker': config.to_dict(),
           'chunk_count': len(cs),
           'chunks': [c.to_dict() for c in cs]}) + '\n')
    (OUT / 'citation_targets.json').write_text(
        j({'chunk_id': example.chunk_id, 'targets': [t.to_dict() for t in targets]}) + '\n')

    # Density per fixture, to show the page-spanning effect is not NRC-specific.
    density = []
    for label, path in [
        ('NRC training manual (baseline)', SAMPLE),
        ('DOE handbook (dense prose)', ROOT / 'fixtures/large/large_doe_nuclear_physics_v1.pdf'),
        ('arXiv paper (two column)', ROOT / 'fixtures/layout/layout_arxiv_two_column_2112.11583.pdf'),
    ]:
        t, pg, h = extract(path)
        h.close()
        cc = chunks(path, config)
        sp = sum(1 for c in cc if c.spans_pages)
        density.append((label, len(pg), round(len(t) / len(pg)), len(cc), sp,
                        f'{sp / len(cc):.0%}', max(len(c.page_spans) for c in cc)))

    checks_rows = '\n'.join(
        f'| `{c.check_id}` | {c.status.value} | {c.message} |'
        for c in result.checks)

    density_rows = '\n'.join(
        f'| {lbl} | {pgs} | {cpp} | {n} | {sp} | {pct} | {mx} |'
        for lbl, pgs, cpp, n, sp, pct, mx in density)

    span_rows = '\n'.join(
        f'| {s.page_number} | `{s.char_start}`–`{s.char_end}` | `{s.page_char_start}`–`{s.page_char_end}` '
        f'| {len(s.highlight_rects)} | {s.coordinates_reliable} |'
        for s in example.page_spans)

    target_rows = '\n'.join(
        f'| {t.page_number} | {len(t.highlight_rects)} | `{t.highlight_rects[0] if t.highlight_rects else "none"}` '
        f'| {t.quoted_text[:48].replace(chr(10), " ")}… |'
        for t in targets)

    md = f'''# Walkthrough: one document, end to end

The Week 1 E2 demo. Every number and every JSON block below is generated by
`tools/build_walkthrough.py` from live output, so nothing here describes an
object the code does not produce. Regenerate with:

```bash
python3 tools/build_walkthrough.py
```

**Sample document:** `{SAMPLE.name}`
NRC Reactor Concepts Manual, Chapter 1. {doc_meta['page_count']} pages,
{doc_meta['byte_size']:,} bytes, {len(text):,} characters of extractable text.

---

## 1. The file becomes a Document

Validation runs first and returns a `ValidationResult`. The `Document` object is
only populated when the file is not rejected, so nothing downstream can
accidentally consume a document that failed import.

```json
{j(doc_meta)}
```

`document_id` is `doc_` plus the SHA-256 of the file bytes. It is
content-addressed, which means the same PDF imported twice under two different
filenames is one document, and any byte change produces a different document
rather than silently mutating an existing one.

### The checks that ran

| check | status | message |
|---|---|---|
{checks_rows}

Every check records what it observed and what it expected, including the ones
that pass. That is what makes the Week 4 regression suite a diff rather than a
rewrite: when a check changes verdict, the report shows the number that moved.

---

## 2. The document becomes a text stream

Text is assembled from layout spans rather than a plain page-by-page dump, and
every character offset maps to a span with a known bounding box **by
construction**. The alternative, extracting text first and searching for
coordinates afterwards, is where highlight drift comes from.

Page boundaries are recorded as offsets into that one stream:

```
page  1  →  chars {pages[0].char_start:>6}–{pages[0].char_end:<6}
page  2  →  chars {pages[1].char_start:>6}–{pages[1].char_end:<6}
page  3  →  chars {pages[2].char_start:>6}–{pages[2].char_end:<6}
...
page {pages[-1].number:>2}  →  chars {pages[-1].char_start:>6}–{pages[-1].char_end:<6}
```

---

## 3. The stream becomes Chunks

Chunker configuration, whose hash participates in every chunk ID:

```json
{j(config.to_dict())}
```

This produced **{len(cs)} chunks**. Here is chunk 0 in full, which is exactly what a
`Chunk` object must contain:

```json
{j(first.to_dict())}
```

### Field by field

| field | why it exists |
|---|---|
| `chunk_id` | `sha256(document_id \\| chunker_config_id \\| char_start \\| char_end)`. A pure function of content and config. Not insertion order, not a UUID, not a timestamp. |
| `document_id` | Resolves the citation back to a file without a separate lookup table. |
| `ordinal` | Reading order for display. Deliberately **not** part of identity, so inserting a page upstream does not renumber every chunk downstream. |
| `text` | What gets embedded and what the model sees. |
| `text_checksum_sha256` | Integrity at index time. A chunk whose text stops hashing to this was corrupted in storage or transit, and that is worth catching before it reaches an answer. |
| `char_start` / `char_end` | Offsets into the document stream, not into a page. This is what makes the text reproducible from the source: `text[char_start:char_end] == chunk.text`, asserted in `tests/test_contracts.py`. |
| `page_start` / `page_end` | The citation range a reader sees. |
| `page_spans` | Per-page provenance and highlight geometry. See section 4. |
| `token_estimate` | Context budgeting for E3. A heuristic (chars / 4), labeled as one so nobody builds an exact budget on it. |
| `chunker_config_id` | Makes the chunk self-describing. Given a chunk you can tell which configuration produced it, which matters when a collection is rebuilt with different settings. |
| `chunker_version` | Same, for code changes rather than config changes. |

---

## 4. Chunks span pages, so `page` cannot be one number

**SDD 5.1 specifies a Chunk as carrying a single page number. On this document
that is wrong for {len(spanning)} of {len(cs)} chunks.**

The NRC manual is slide-style, averaging about
{round(len(text) / doc_meta['page_count'])} characters per page, so a
{config.target_chars}-character chunk covers two to four pages. A single `page`
field would make citations point at whichever page happened to be chosen, and
roughly half of them would point at the wrong one.

| document | pages | chars/page | chunks | chunks spanning pages | share | max pages in one chunk |
|---|---|---|---|---|---|---|
{density_rows}

It is not an NRC quirk. It shows up on dense prose too, because a chunk boundary
has no reason to coincide with a page boundary.

The fix is `page_spans`: one entry per page the chunk touches. Chunk
`{example.chunk_id}` spans pages {example.page_start}–{example.page_end}:

| page | document offsets | page-local offsets | highlight rects | coords reliable |
|---|---|---|---|---|
{span_rows}

Page-local offsets are included so E4 can render one page in isolation without
re-deriving where that page started in the stream.

**Recommendation for the SDD:** change the Chunk record in 5.1 from a page
number to a page range plus per-page spans. Per SDD 17.2 this needs an SDD
update before implementation, and it affects the citation payload E3 finalizes
in Week 6.

---

## 5. A Chunk becomes a Citation

SDD 7.3 requires a citation to identify document and page, expand into a
rendering of that page, and highlight the supporting passage where reliable
coordinates exist. All three are satisfiable from `page_spans` alone, with no
second pass over the PDF.

One chunk spanning {len(targets)} pages expands into {len(targets)} citation targets:

| page | rects | first rect (PDF points) | quoted text |
|---|---|---|---|
{target_rows}

```json
{j(targets[0].to_dict())}
```

Rectangles are merged per text line, so a passage crossing three lines renders as
three boxes rather than one block covering the paragraph between them.
`page_width` and `page_height` ride along so the UI can normalize against its own
render scale, and `coordinates_reliable` tells E4 when to cite the page without
attempting a highlight.

---

## 6. Why the IDs are stable

Run the chunker twice on the same file with the same config and every ID is
identical. Copy the file, rename it, run again: still identical, because identity
is content-addressed rather than path-based.

That is what lets SDD 5.1's promise hold, that historical conversations retain
their original collection version: a citation stored in a conversation three
weeks ago still resolves after the collection is republished, as long as the
document bytes and the chunker config did not change. When either does change,
every affected ID changes too, which is the honest outcome. A stale citation
that silently points at moved text is worse than one that fails loudly.

Proven in `tests/test_contracts.py`:

```
test_same_file_and_config_yield_same_ids   chunk IDs reproduce exactly across runs
test_reindex_preserves_ids                 {len(cs)} chunk IDs survive re-import under a different filename
test_config_change_changes_every_id        no ID collisions across configs
test_offsets_reconstruct_chunk_text        offsets reproduce chunk text on every chunk
test_page_spans_tile_the_chunk             page spans tile every chunk contiguously
```

---

## Artifacts

| file | contents |
|---|---|
| `walkthrough/validation_result.json` | full ValidationResult for the sample |
| `walkthrough/document.json` | the Document object |
| `walkthrough/chunk_000.json` | one Chunk in full |
| `walkthrough/all_chunks.json` | all {len(cs)} chunks |
| `walkthrough/citation_targets.json` | citation targets from one page-spanning chunk |
'''

    (ROOT / 'WALKTHROUGH.md').write_text(md)
    print(f'wrote WALKTHROUGH.md  ({len(md.splitlines())} lines)')
    for p in sorted(OUT.glob('*.json')):
        print(f'  {p.relative_to(ROOT)}  ({p.stat().st_size:,} bytes)')


if __name__ == '__main__':
    main()
